// Peripheral: SAI_Periph  Serial Audio Interface.
// Instances:
//  SAI1  mmap.SAI1_BASE
// Registers:
//  0x00 32  GCR Global configuration register.
// Import:
//  /Users/ian/code/src/github.com/ianmcmahon/emgo/egpath/src/stm32/o/f469xx/mmap
package sai

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.

const (
	SYNCIN  GCR = 0x03 << 0 //+ SYNCIN[1:0] bits (Synchronization Inputs).
	SYNCOUT GCR = 0x03 << 4 //+ SYNCOUT[1:0] bits (Synchronization Outputs).
)

const (
	SYNCINn  = 0
	SYNCOUTn = 4
)
