// Peripheral: CAN_TxMailBox_Periph  Controller Area Network TxMailBox.
// Instances:
// Registers:
//  0x00 32  TIR  CAN TX mailbox identifier register.
//  0x04 32  TDTR CAN mailbox data length control and time stamp register.
//  0x08 32  TDLR CAN mailbox data low register.
//  0x0C 32  TDHR CAN mailbox data high register.
// Import:
//  /Users/ian/code/src/github.com/ianmcmahon/emgo/egpath/src/stm32/o/f469xx/mmap
package can

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.
