// Peripheral: GPIO_Periph  General Purpose I/O.
// Instances:
//  GPIOA  mmap.GPIOA_BASE
//  GPIOB  mmap.GPIOB_BASE
//  GPIOC  mmap.GPIOC_BASE
//  GPIOD  mmap.GPIOD_BASE
//  GPIOE  mmap.GPIOE_BASE
//  GPIOF  mmap.GPIOF_BASE
//  GPIOG  mmap.GPIOG_BASE
//  GPIOH  mmap.GPIOH_BASE
//  GPIOI  mmap.GPIOI_BASE
//  GPIOJ  mmap.GPIOJ_BASE
//  GPIOK  mmap.GPIOK_BASE
// Registers:
//  0x00 32  MODER   Port mode register.
//  0x04 32  OTYPER  Port output type register.
//  0x08 32  OSPEEDR Port output speed register.
//  0x0C 32  PUPDR   Port pull-up/pull-down register.
//  0x10 32  IDR     Port input data register.
//  0x14 32  ODR     Port output data register.
//  0x18 32  BSRR    Port bit set/reset register.
//  0x1C 32  LCKR    Port configuration lock register.
//  0x20 32  AFR[2]  Alternate function registers.
// Import:
//  stm32/o/f746xx/mmap
package gpio

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.

const (
	MODER0  MODER = 0x03 << 0  //+
	MODER1  MODER = 0x03 << 2  //+
	MODER2  MODER = 0x03 << 4  //+
	MODER3  MODER = 0x03 << 6  //+
	MODER4  MODER = 0x03 << 8  //+
	MODER5  MODER = 0x03 << 10 //+
	MODER6  MODER = 0x03 << 12 //+
	MODER7  MODER = 0x03 << 14 //+
	MODER8  MODER = 0x03 << 16 //+
	MODER9  MODER = 0x03 << 18 //+
	MODER10 MODER = 0x03 << 20 //+
	MODER11 MODER = 0x03 << 22 //+
	MODER12 MODER = 0x03 << 24 //+
	MODER13 MODER = 0x03 << 26 //+
	MODER14 MODER = 0x03 << 28 //+
	MODER15 MODER = 0x03 << 30 //+
)

const (
	MODER0n  = 0
	MODER1n  = 2
	MODER2n  = 4
	MODER3n  = 6
	MODER4n  = 8
	MODER5n  = 10
	MODER6n  = 12
	MODER7n  = 14
	MODER8n  = 16
	MODER9n  = 18
	MODER10n = 20
	MODER11n = 22
	MODER12n = 24
	MODER13n = 26
	MODER14n = 28
	MODER15n = 30
)

const (
	OT_10 OTYPER = 0x01 << 10 //+
	OT_11 OTYPER = 0x01 << 11 //+
	OT_12 OTYPER = 0x01 << 12 //+
	OT_13 OTYPER = 0x01 << 13 //+
	OT_14 OTYPER = 0x01 << 14 //+
	OT_15 OTYPER = 0x01 << 15 //+
)

const (
	OT_10n = 10
	OT_11n = 11
	OT_12n = 12
	OT_13n = 13
	OT_14n = 14
	OT_15n = 15
)

const (
	PUPDR0  PUPDR = 0x03 << 0  //+
	PUPDR1  PUPDR = 0x03 << 2  //+
	PUPDR2  PUPDR = 0x03 << 4  //+
	PUPDR3  PUPDR = 0x03 << 6  //+
	PUPDR4  PUPDR = 0x03 << 8  //+
	PUPDR5  PUPDR = 0x03 << 10 //+
	PUPDR6  PUPDR = 0x03 << 12 //+
	PUPDR7  PUPDR = 0x03 << 14 //+
	PUPDR8  PUPDR = 0x03 << 16 //+
	PUPDR9  PUPDR = 0x03 << 18 //+
	PUPDR10 PUPDR = 0x03 << 20 //+
	PUPDR11 PUPDR = 0x03 << 22 //+
	PUPDR12 PUPDR = 0x03 << 24 //+
	PUPDR13 PUPDR = 0x03 << 26 //+
	PUPDR14 PUPDR = 0x03 << 28 //+
	PUPDR15 PUPDR = 0x03 << 30 //+
)

const (
	PUPDR0n  = 0
	PUPDR1n  = 2
	PUPDR2n  = 4
	PUPDR3n  = 6
	PUPDR4n  = 8
	PUPDR5n  = 10
	PUPDR6n  = 12
	PUPDR7n  = 14
	PUPDR8n  = 16
	PUPDR9n  = 18
	PUPDR10n = 20
	PUPDR11n = 22
	PUPDR12n = 24
	PUPDR13n = 26
	PUPDR14n = 28
	PUPDR15n = 30
)

const (
	IDR_10 IDR = 0x01 << 10 //+
	IDR_11 IDR = 0x01 << 11 //+
	IDR_12 IDR = 0x01 << 12 //+
	IDR_13 IDR = 0x01 << 13 //+
	IDR_14 IDR = 0x01 << 14 //+
	IDR_15 IDR = 0x01 << 15 //+
)

const (
	IDR_10n = 10
	IDR_11n = 11
	IDR_12n = 12
	IDR_13n = 13
	IDR_14n = 14
	IDR_15n = 15
)

const (
	ODR_10 ODR = 0x01 << 10 //+
	ODR_11 ODR = 0x01 << 11 //+
	ODR_12 ODR = 0x01 << 12 //+
	ODR_13 ODR = 0x01 << 13 //+
	ODR_14 ODR = 0x01 << 14 //+
	ODR_15 ODR = 0x01 << 15 //+
)

const (
	ODR_10n = 10
	ODR_11n = 11
	ODR_12n = 12
	ODR_13n = 13
	ODR_14n = 14
	ODR_15n = 15
)

const (
	BS_10 BSRR = 0x01 << 10 //+
	BS_11 BSRR = 0x01 << 11 //+
	BS_12 BSRR = 0x01 << 12 //+
	BS_13 BSRR = 0x01 << 13 //+
	BS_14 BSRR = 0x01 << 14 //+
	BS_15 BSRR = 0x01 << 15 //+
	BR_10 BSRR = 0x01 << 26 //+
	BR_11 BSRR = 0x01 << 27 //+
	BR_12 BSRR = 0x01 << 28 //+
	BR_13 BSRR = 0x01 << 29 //+
	BR_14 BSRR = 0x01 << 30 //+
	BR_15 BSRR = 0x01 << 31 //+
)

const (
	BS_10n = 10
	BS_11n = 11
	BS_12n = 12
	BS_13n = 13
	BS_14n = 14
	BS_15n = 15
	BR_10n = 26
	BR_11n = 27
	BR_12n = 28
	BR_13n = 29
	BR_14n = 30
	BR_15n = 31
)

const (
	LCK0  LCKR = 0x01 << 0  //+
	LCK1  LCKR = 0x01 << 1  //+
	LCK2  LCKR = 0x01 << 2  //+
	LCK3  LCKR = 0x01 << 3  //+
	LCK4  LCKR = 0x01 << 4  //+
	LCK5  LCKR = 0x01 << 5  //+
	LCK6  LCKR = 0x01 << 6  //+
	LCK7  LCKR = 0x01 << 7  //+
	LCK8  LCKR = 0x01 << 8  //+
	LCK9  LCKR = 0x01 << 9  //+
	LCK10 LCKR = 0x01 << 10 //+
	LCK11 LCKR = 0x01 << 11 //+
	LCK12 LCKR = 0x01 << 12 //+
	LCK13 LCKR = 0x01 << 13 //+
	LCK14 LCKR = 0x01 << 14 //+
	LCK15 LCKR = 0x01 << 15 //+
	LCKK  LCKR = 0x01 << 16 //+
)

const (
	LCK0n  = 0
	LCK1n  = 1
	LCK2n  = 2
	LCK3n  = 3
	LCK4n  = 4
	LCK5n  = 5
	LCK6n  = 6
	LCK7n  = 7
	LCK8n  = 8
	LCK9n  = 9
	LCK10n = 10
	LCK11n = 11
	LCK12n = 12
	LCK13n = 13
	LCK14n = 14
	LCK15n = 15
	LCKKn  = 16
)
